// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetAllShipmentsResponse.proto

package BeeGees_Queries_Responses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllShipmentsResponse struct {
	CustomerId           int32                               `protobuf:"varint,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	Shipments            []*GetAllShipmentsResponse_Shipment `protobuf:"bytes,2,rep,name=Shipments,proto3" json:"Shipments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetAllShipmentsResponse) Reset()         { *m = GetAllShipmentsResponse{} }
func (m *GetAllShipmentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllShipmentsResponse) ProtoMessage()    {}
func (*GetAllShipmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cfcfd626ec459bf, []int{0}
}

func (m *GetAllShipmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllShipmentsResponse.Unmarshal(m, b)
}
func (m *GetAllShipmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllShipmentsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllShipmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllShipmentsResponse.Merge(m, src)
}
func (m *GetAllShipmentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllShipmentsResponse.Size(m)
}
func (m *GetAllShipmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllShipmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllShipmentsResponse proto.InternalMessageInfo

func (m *GetAllShipmentsResponse) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *GetAllShipmentsResponse) GetShipments() []*GetAllShipmentsResponse_Shipment {
	if m != nil {
		return m.Shipments
	}
	return nil
}

type GetAllShipmentsResponse_Shipment struct {
	CustomerId           int32    `protobuf:"varint,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	FinalDestination     string   `protobuf:"bytes,2,opt,name=FinalDestination,proto3" json:"FinalDestination,omitempty"`
	CurrentLocation      string   `protobuf:"bytes,3,opt,name=CurrentLocation,proto3" json:"CurrentLocation,omitempty"`
	PurchaseTime         string   `protobuf:"bytes,4,opt,name=PurchaseTime,proto3" json:"PurchaseTime,omitempty"`
	LastStatusUpdate     string   `protobuf:"bytes,5,opt,name=LastStatusUpdate,proto3" json:"LastStatusUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllShipmentsResponse_Shipment) Reset()         { *m = GetAllShipmentsResponse_Shipment{} }
func (m *GetAllShipmentsResponse_Shipment) String() string { return proto.CompactTextString(m) }
func (*GetAllShipmentsResponse_Shipment) ProtoMessage()    {}
func (*GetAllShipmentsResponse_Shipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cfcfd626ec459bf, []int{0, 0}
}

func (m *GetAllShipmentsResponse_Shipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllShipmentsResponse_Shipment.Unmarshal(m, b)
}
func (m *GetAllShipmentsResponse_Shipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllShipmentsResponse_Shipment.Marshal(b, m, deterministic)
}
func (m *GetAllShipmentsResponse_Shipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllShipmentsResponse_Shipment.Merge(m, src)
}
func (m *GetAllShipmentsResponse_Shipment) XXX_Size() int {
	return xxx_messageInfo_GetAllShipmentsResponse_Shipment.Size(m)
}
func (m *GetAllShipmentsResponse_Shipment) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllShipmentsResponse_Shipment.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllShipmentsResponse_Shipment proto.InternalMessageInfo

func (m *GetAllShipmentsResponse_Shipment) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *GetAllShipmentsResponse_Shipment) GetFinalDestination() string {
	if m != nil {
		return m.FinalDestination
	}
	return ""
}

func (m *GetAllShipmentsResponse_Shipment) GetCurrentLocation() string {
	if m != nil {
		return m.CurrentLocation
	}
	return ""
}

func (m *GetAllShipmentsResponse_Shipment) GetPurchaseTime() string {
	if m != nil {
		return m.PurchaseTime
	}
	return ""
}

func (m *GetAllShipmentsResponse_Shipment) GetLastStatusUpdate() string {
	if m != nil {
		return m.LastStatusUpdate
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAllShipmentsResponse)(nil), "BeeGees.Queries.Responses.GetAllShipmentsResponse")
	proto.RegisterType((*GetAllShipmentsResponse_Shipment)(nil), "BeeGees.Queries.Responses.GetAllShipmentsResponse.Shipment")
}

func init() { proto.RegisterFile("GetAllShipmentsResponse.proto", fileDescriptor_2cfcfd626ec459bf) }

var fileDescriptor_2cfcfd626ec459bf = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0xad, 0x15, 0x3b, 0x0a, 0x4a, 0x2e, 0x46, 0x41, 0x59, 0x7a, 0x0a, 0x1e, 0x72,
	0xd0, 0xa3, 0x27, 0xad, 0x58, 0x84, 0x1e, 0x34, 0xd5, 0x83, 0xc7, 0xd8, 0x0e, 0x34, 0xb0, 0x9b,
	0x84, 0xcc, 0xe4, 0x7b, 0xfa, 0x2d, 0xfc, 0x1a, 0xe2, 0x96, 0xf5, 0x4f, 0x65, 0xe9, 0x71, 0x7e,
	0xf3, 0xde, 0xbc, 0x07, 0x03, 0x67, 0x53, 0xe4, 0x9b, 0xba, 0x9e, 0xaf, 0x5c, 0x6c, 0xd0, 0x33,
	0x19, 0xa4, 0x18, 0x3c, 0xa1, 0x8e, 0x29, 0x70, 0x10, 0x27, 0xb7, 0x88, 0x53, 0x44, 0xd2, 0x4f,
	0x19, 0x93, 0x43, 0xd2, 0xdd, 0x9e, 0xc6, 0x1f, 0x25, 0x1c, 0xf7, 0x98, 0xc5, 0x39, 0xc0, 0x24,
	0x13, 0x87, 0x06, 0xd3, 0xc3, 0x52, 0x16, 0x55, 0xa1, 0x86, 0xe6, 0x17, 0x11, 0xaf, 0x30, 0xfa,
	0x36, 0xc9, 0xb2, 0x1a, 0xa8, 0xfd, 0xcb, 0x6b, 0xdd, 0x1b, 0xa5, 0xfb, 0x3a, 0x76, 0xc4, 0xfc,
	0x5c, 0x3b, 0x7d, 0x2f, 0x60, 0xaf, 0x9b, 0xb6, 0xf6, 0xb8, 0x80, 0xa3, 0x7b, 0xe7, 0x6d, 0x7d,
	0x87, 0xc4, 0xce, 0x5b, 0x76, 0xc1, 0xcb, 0xb2, 0x2a, 0xd4, 0xc8, 0xfc, 0xe3, 0x42, 0xc1, 0xe1,
	0x24, 0xa7, 0x84, 0x9e, 0x67, 0x61, 0xb1, 0x96, 0x0e, 0x5a, 0xe9, 0x26, 0x16, 0x63, 0x38, 0x78,
	0xcc, 0x69, 0xb1, 0xb2, 0x84, 0xcf, 0xae, 0x41, 0xb9, 0xd3, 0xca, 0xfe, 0xb0, 0xaf, 0xe4, 0x99,
	0x25, 0x9e, 0xb3, 0xe5, 0x4c, 0x2f, 0x71, 0x69, 0x19, 0xe5, 0x70, 0x9d, 0xbc, 0xc9, 0xdf, 0x76,
	0xdb, 0x5f, 0x5c, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x21, 0xd3, 0x3e, 0x7d, 0xac, 0x01, 0x00,
	0x00,
}
