// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetShipmentStatusResponse.proto

package BeeGees_Queries_Responses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetShipmentStatusResponse struct {
	ShipmentId           string   `protobuf:"bytes,1,opt,name=ShipmentId,proto3" json:"ShipmentId,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
	LastUpdated          string   `protobuf:"bytes,4,opt,name=LastUpdated,proto3" json:"LastUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipmentStatusResponse) Reset()         { *m = GetShipmentStatusResponse{} }
func (m *GetShipmentStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetShipmentStatusResponse) ProtoMessage()    {}
func (*GetShipmentStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa365cb2780bdb89, []int{0}
}

func (m *GetShipmentStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipmentStatusResponse.Unmarshal(m, b)
}
func (m *GetShipmentStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipmentStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetShipmentStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipmentStatusResponse.Merge(m, src)
}
func (m *GetShipmentStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetShipmentStatusResponse.Size(m)
}
func (m *GetShipmentStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipmentStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipmentStatusResponse proto.InternalMessageInfo

func (m *GetShipmentStatusResponse) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *GetShipmentStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetShipmentStatusResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GetShipmentStatusResponse) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

func init() {
	proto.RegisterType((*GetShipmentStatusResponse)(nil), "BeeGees.Queries.Responses.GetShipmentStatusResponse")
}

func init() { proto.RegisterFile("GetShipmentStatusResponse.proto", fileDescriptor_fa365cb2780bdb89) }

var fileDescriptor_fa365cb2780bdb89 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x77, 0x4f, 0x2d, 0x09,
	0xce, 0xc8, 0x2c, 0xc8, 0x4d, 0xcd, 0x2b, 0x09, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x0e, 0x4a, 0x2d,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x74, 0x4a, 0x4d,
	0x75, 0x4f, 0x4d, 0x2d, 0xd6, 0x0b, 0x2c, 0x4d, 0x2d, 0xca, 0x4c, 0x2d, 0xd6, 0x83, 0xc9, 0x17,
	0x2b, 0x4d, 0x64, 0xe4, 0x92, 0xc4, 0xa9, 0x5d, 0x48, 0x8e, 0x8b, 0x0b, 0x26, 0xe3, 0x99, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x24, 0x22, 0x24, 0xc6, 0xc5, 0x06, 0xd1, 0x21, 0xc1,
	0x04, 0x96, 0x83, 0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x7c, 0xf2, 0x93, 0x13, 0x4b, 0x32, 0xf3, 0xf3,
	0x24, 0x98, 0xc1, 0x32, 0x70, 0xbe, 0x90, 0x02, 0x17, 0xb7, 0x4f, 0x62, 0x71, 0x49, 0x68, 0x41,
	0x4a, 0x62, 0x49, 0x6a, 0x8a, 0x04, 0x0b, 0x58, 0x1a, 0x59, 0x28, 0x89, 0x0d, 0xec, 0x6a, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x76, 0x91, 0xd8, 0xd8, 0x00, 0x00, 0x00,
}
