// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UpdateShipmentStatusCommand.proto

package BeeGees_Commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateShipmentCommand struct {
	ShipmentId           string   `protobuf:"bytes,1,opt,name=ShipmentId,proto3" json:"ShipmentId,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateShipmentCommand) Reset()         { *m = UpdateShipmentCommand{} }
func (m *UpdateShipmentCommand) String() string { return proto.CompactTextString(m) }
func (*UpdateShipmentCommand) ProtoMessage()    {}
func (*UpdateShipmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_429f9de961d3e816, []int{0}
}

func (m *UpdateShipmentCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShipmentCommand.Unmarshal(m, b)
}
func (m *UpdateShipmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShipmentCommand.Marshal(b, m, deterministic)
}
func (m *UpdateShipmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShipmentCommand.Merge(m, src)
}
func (m *UpdateShipmentCommand) XXX_Size() int {
	return xxx_messageInfo_UpdateShipmentCommand.Size(m)
}
func (m *UpdateShipmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShipmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShipmentCommand proto.InternalMessageInfo

func (m *UpdateShipmentCommand) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *UpdateShipmentCommand) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateShipmentCommand) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateShipmentCommand)(nil), "BeeGees.Commands.UpdateShipmentCommand")
}

func init() { proto.RegisterFile("UpdateShipmentStatusCommand.proto", fileDescriptor_429f9de961d3e816) }

var fileDescriptor_429f9de961d3e816 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x0c, 0x2d, 0x48, 0x49,
	0x2c, 0x49, 0x0d, 0xce, 0xc8, 0x2c, 0xc8, 0x4d, 0xcd, 0x2b, 0x09, 0x2e, 0x49, 0x2c, 0x29, 0x2d,
	0x76, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x70,
	0x4a, 0x4d, 0x75, 0x4f, 0x4d, 0x2d, 0xd6, 0x83, 0x0a, 0x17, 0x2b, 0x65, 0x73, 0x89, 0xa2, 0x6a,
	0x83, 0xca, 0x08, 0xc9, 0x71, 0x71, 0xc1, 0x84, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x90, 0x44, 0x84, 0xc4, 0xb8, 0xd8, 0x20, 0x36, 0x48, 0x30, 0x81, 0xe5, 0xa0, 0x3c, 0x21,
	0x29, 0x2e, 0x0e, 0x9f, 0xfc, 0xe4, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x66, 0xb0, 0x0c, 0x9c,
	0x9f, 0xc4, 0x06, 0x76, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x50, 0x30, 0x88, 0x0b, 0xaa,
	0x00, 0x00, 0x00,
}
