// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetShipmentStatusQuery.proto

package BeeGees_Queries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetShipmentStatusQuery struct {
	ShipmentId           string   `protobuf:"bytes,1,opt,name=ShipmentId,proto3" json:"ShipmentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipmentStatusQuery) Reset()         { *m = GetShipmentStatusQuery{} }
func (m *GetShipmentStatusQuery) String() string { return proto.CompactTextString(m) }
func (*GetShipmentStatusQuery) ProtoMessage()    {}
func (*GetShipmentStatusQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_59ad274712931fd7, []int{0}
}

func (m *GetShipmentStatusQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipmentStatusQuery.Unmarshal(m, b)
}
func (m *GetShipmentStatusQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipmentStatusQuery.Marshal(b, m, deterministic)
}
func (m *GetShipmentStatusQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipmentStatusQuery.Merge(m, src)
}
func (m *GetShipmentStatusQuery) XXX_Size() int {
	return xxx_messageInfo_GetShipmentStatusQuery.Size(m)
}
func (m *GetShipmentStatusQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipmentStatusQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipmentStatusQuery proto.InternalMessageInfo

func (m *GetShipmentStatusQuery) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetShipmentStatusQuery)(nil), "BeeGees.Queries.GetShipmentStatusQuery")
}

func init() { proto.RegisterFile("GetShipmentStatusQuery.proto", fileDescriptor_59ad274712931fd7) }

var fileDescriptor_59ad274712931fd7 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x71, 0x4f, 0x2d, 0x09,
	0xce, 0xc8, 0x2c, 0xc8, 0x4d, 0xcd, 0x2b, 0x09, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x0e, 0x2c, 0x4d,
	0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x77, 0x4a, 0x4d, 0x75, 0x4f, 0x4d,
	0x2d, 0xd6, 0x03, 0x09, 0x66, 0xa6, 0x16, 0x2b, 0x59, 0x70, 0x89, 0x61, 0xd7, 0x20, 0x24, 0xc7,
	0xc5, 0x05, 0x13, 0xf6, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x12, 0x49, 0x62,
	0x03, 0x9b, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xd7, 0xc6, 0x96, 0x71, 0x00, 0x00,
	0x00,
}
