// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ShipmentDeliveredEvent.proto

package BeeGees_Events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipmentDeliveredEvent struct {
	ShipmentId           string   `protobuf:"bytes,1,opt,name=ShipmentId,proto3" json:"ShipmentId,omitempty"`
	DeliveredDate        int64    `protobuf:"varint,2,opt,name=DeliveredDate,proto3" json:"DeliveredDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentDeliveredEvent) Reset()         { *m = ShipmentDeliveredEvent{} }
func (m *ShipmentDeliveredEvent) String() string { return proto.CompactTextString(m) }
func (*ShipmentDeliveredEvent) ProtoMessage()    {}
func (*ShipmentDeliveredEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_501fea1fc66fb0ff, []int{0}
}

func (m *ShipmentDeliveredEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentDeliveredEvent.Unmarshal(m, b)
}
func (m *ShipmentDeliveredEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentDeliveredEvent.Marshal(b, m, deterministic)
}
func (m *ShipmentDeliveredEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentDeliveredEvent.Merge(m, src)
}
func (m *ShipmentDeliveredEvent) XXX_Size() int {
	return xxx_messageInfo_ShipmentDeliveredEvent.Size(m)
}
func (m *ShipmentDeliveredEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentDeliveredEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentDeliveredEvent proto.InternalMessageInfo

func (m *ShipmentDeliveredEvent) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *ShipmentDeliveredEvent) GetDeliveredDate() int64 {
	if m != nil {
		return m.DeliveredDate
	}
	return 0
}

func init() {
	proto.RegisterType((*ShipmentDeliveredEvent)(nil), "BeeGees.Events.ShipmentDeliveredEvent")
}

func init() { proto.RegisterFile("ShipmentDeliveredEvent.proto", fileDescriptor_501fea1fc66fb0ff) }

var fileDescriptor_501fea1fc66fb0ff = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x09, 0xce, 0xc8, 0x2c,
	0xc8, 0x4d, 0xcd, 0x2b, 0x71, 0x49, 0xcd, 0xc9, 0x2c, 0x4b, 0x2d, 0x4a, 0x4d, 0x71, 0x2d, 0x4b,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x73, 0x4a, 0x4d, 0x75, 0x4f, 0x4d,
	0x2d, 0xd6, 0x03, 0x0b, 0x16, 0x2b, 0xc5, 0x71, 0x89, 0x61, 0x57, 0x2f, 0x24, 0xc7, 0xc5, 0x05,
	0x93, 0xf1, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x12, 0x11, 0x52, 0xe1, 0xe2,
	0x85, 0xeb, 0x70, 0x49, 0x2c, 0x49, 0x95, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0e, 0x42, 0x15, 0x4c,
	0x62, 0x03, 0x5b, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x00, 0x5f, 0x77, 0x96, 0x00,
	0x00, 0x00,
}
