// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ShipmentUpdatedResponse.proto

package BeeGees_Commands_Responses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipmentUpdatedResponse struct {
	ShipmentId           string   `protobuf:"bytes,1,opt,name=ShipmentId,proto3" json:"ShipmentId,omitempty"`
	ShipmentName         string   `protobuf:"bytes,2,opt,name=ShipmentName,proto3" json:"ShipmentName,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentUpdatedResponse) Reset()         { *m = ShipmentUpdatedResponse{} }
func (m *ShipmentUpdatedResponse) String() string { return proto.CompactTextString(m) }
func (*ShipmentUpdatedResponse) ProtoMessage()    {}
func (*ShipmentUpdatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a86995c71756697a, []int{0}
}

func (m *ShipmentUpdatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentUpdatedResponse.Unmarshal(m, b)
}
func (m *ShipmentUpdatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentUpdatedResponse.Marshal(b, m, deterministic)
}
func (m *ShipmentUpdatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentUpdatedResponse.Merge(m, src)
}
func (m *ShipmentUpdatedResponse) XXX_Size() int {
	return xxx_messageInfo_ShipmentUpdatedResponse.Size(m)
}
func (m *ShipmentUpdatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentUpdatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentUpdatedResponse proto.InternalMessageInfo

func (m *ShipmentUpdatedResponse) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *ShipmentUpdatedResponse) GetShipmentName() string {
	if m != nil {
		return m.ShipmentName
	}
	return ""
}

func (m *ShipmentUpdatedResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ShipmentUpdatedResponse)(nil), "BeeGees.Commands.Responses.ShipmentUpdatedResponse")
}

func init() { proto.RegisterFile("ShipmentUpdatedResponse.proto", fileDescriptor_a86995c71756697a) }

var fileDescriptor_a86995c71756697a = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0d, 0xce, 0xc8, 0x2c,
	0xc8, 0x4d, 0xcd, 0x2b, 0x09, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x4d, 0x09, 0x4a, 0x2d, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x72, 0x4a, 0x4d, 0x75, 0x4f,
	0x4d, 0x2d, 0xd6, 0x73, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x83, 0x29, 0x28, 0x56,
	0x2a, 0xe7, 0x12, 0xc7, 0xa1, 0x59, 0x48, 0x8e, 0x8b, 0x0b, 0x26, 0xe5, 0x99, 0x22, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x24, 0x22, 0xa4, 0xc4, 0xc5, 0x03, 0xe3, 0xf9, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x81, 0x55, 0xa0, 0x88, 0x09, 0x49, 0x70, 0xb1, 0x07, 0x97, 0x26, 0x27, 0xa7, 0x16,
	0x17, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x04, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0xb7, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x18, 0x98, 0x10, 0xd5, 0xbc, 0x00, 0x00, 0x00,
}
