// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ShipmentCreatedResponse.proto

package BeeGees_Commands_Responses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipmentCreatedResponse struct {
	ShipmentId           string   `protobuf:"bytes,1,opt,name=ShipmentId,proto3" json:"ShipmentId,omitempty"`
	CreatedDate          string   `protobuf:"bytes,2,opt,name=CreatedDate,proto3" json:"CreatedDate,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentCreatedResponse) Reset()         { *m = ShipmentCreatedResponse{} }
func (m *ShipmentCreatedResponse) String() string { return proto.CompactTextString(m) }
func (*ShipmentCreatedResponse) ProtoMessage()    {}
func (*ShipmentCreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69d0b6888c8a8a7a, []int{0}
}

func (m *ShipmentCreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentCreatedResponse.Unmarshal(m, b)
}
func (m *ShipmentCreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentCreatedResponse.Marshal(b, m, deterministic)
}
func (m *ShipmentCreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentCreatedResponse.Merge(m, src)
}
func (m *ShipmentCreatedResponse) XXX_Size() int {
	return xxx_messageInfo_ShipmentCreatedResponse.Size(m)
}
func (m *ShipmentCreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentCreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentCreatedResponse proto.InternalMessageInfo

func (m *ShipmentCreatedResponse) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *ShipmentCreatedResponse) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *ShipmentCreatedResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ShipmentCreatedResponse)(nil), "BeeGees.Commands.Responses.ShipmentCreatedResponse")
}

func init() { proto.RegisterFile("ShipmentCreatedResponse.proto", fileDescriptor_69d0b6888c8a8a7a) }

var fileDescriptor_69d0b6888c8a8a7a = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0d, 0xce, 0xc8, 0x2c,
	0xc8, 0x4d, 0xcd, 0x2b, 0x71, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x09, 0x4a, 0x2d, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x72, 0x4a, 0x4d, 0x75, 0x4f,
	0x4d, 0x2d, 0xd6, 0x73, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x83, 0x29, 0x28, 0x56,
	0x2a, 0xe5, 0x12, 0xc7, 0xa1, 0x59, 0x48, 0x8e, 0x8b, 0x0b, 0x26, 0xe5, 0x99, 0x22, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x24, 0x22, 0xa4, 0xc0, 0xc5, 0x0d, 0xd5, 0xe2, 0x92, 0x58, 0x92,
	0x2a, 0xc1, 0x04, 0x56, 0x80, 0x2c, 0x24, 0x24, 0xc1, 0xc5, 0x1e, 0x5c, 0x9a, 0x9c, 0x9c, 0x5a,
	0x5c, 0x2c, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe3, 0x26, 0xb1, 0x81, 0x5d, 0x66, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x3d, 0x7e, 0xaa, 0xba, 0x00, 0x00, 0x00,
}
