// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WriterNotify.proto

package BeeGees

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WriterNotify struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Blob                 []byte   `protobuf:"bytes,2,opt,name=Blob,proto3" json:"Blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriterNotify) Reset()         { *m = WriterNotify{} }
func (m *WriterNotify) String() string { return proto.CompactTextString(m) }
func (*WriterNotify) ProtoMessage()    {}
func (*WriterNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_151534f565762891, []int{0}
}

func (m *WriterNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriterNotify.Unmarshal(m, b)
}
func (m *WriterNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriterNotify.Marshal(b, m, deterministic)
}
func (m *WriterNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriterNotify.Merge(m, src)
}
func (m *WriterNotify) XXX_Size() int {
	return xxx_messageInfo_WriterNotify.Size(m)
}
func (m *WriterNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_WriterNotify.DiscardUnknown(m)
}

var xxx_messageInfo_WriterNotify proto.InternalMessageInfo

func (m *WriterNotify) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *WriterNotify) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func init() {
	proto.RegisterType((*WriterNotify)(nil), "BeeGees.WriterNotify")
}

func init() { proto.RegisterFile("WriterNotify.proto", fileDescriptor_151534f565762891) }

var fileDescriptor_151534f565762891 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x2f, 0xca, 0x2c,
	0x49, 0x2d, 0xf2, 0xcb, 0x2f, 0xc9, 0x4c, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x77, 0x4a, 0x4d, 0x75, 0x4f, 0x4d, 0x2d, 0x56, 0x32, 0xe3, 0xe2, 0x41, 0x96, 0x16, 0x12, 0xe2,
	0x62, 0x09, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x41, 0x62,
	0x4e, 0x39, 0xf9, 0x49, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0x76, 0x12, 0x1b, 0xd8,
	0x1c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x14, 0x0a, 0x06, 0x5d, 0x00, 0x00, 0x00,
}
